-- Ember initial schema. Mirrors the JPA entities (com.ember.domain) exactly so that
-- prod can run with `spring.jpa.hibernate.ddl-auto=validate`. The column types match
-- what Hibernate generates for the PostgreSQL dialect (notably: money is numeric(_,2)
-- and lifecycle timestamps are `timestamp with time zone` for the Instant fields).

create table menu_item (
    id             varchar(255)  not null,
    name           varchar(255)  not null,
    category       varchar(255)  not null,
    base_price     numeric(8, 2) not null,
    meal_available boolean       not null,
    primary key (id)
);

-- @ElementCollection of PriceModifier (size options) on MenuItem
create table menu_item_size (
    menu_item_id varchar(255)  not null,
    label        varchar(255)  not null,
    price_delta  numeric(8, 2) not null,
    constraint fk_menu_item_size_menu_item
        foreign key (menu_item_id) references menu_item
);

-- @ElementCollection of PriceModifier (add-on options) on MenuItem
create table menu_item_addon (
    menu_item_id varchar(255)  not null,
    label        varchar(255)  not null,
    price_delta  numeric(8, 2) not null,
    constraint fk_menu_item_addon_menu_item
        foreign key (menu_item_id) references menu_item
);

create table orders (
    id            bigint         generated by default as identity,
    ticket_number integer        not null,
    type          varchar(255)   not null,
    status        varchar(255)   not null,
    subtotal      numeric(10, 2) not null,
    tax           numeric(10, 2) not null,
    total         numeric(10, 2) not null,
    created_at    timestamp(6) with time zone not null,
    started_at    timestamp(6) with time zone,
    ready_at      timestamp(6) with time zone,
    collected_at  timestamp(6) with time zone,
    primary key (id)
);

create table order_line (
    id           bigint         generated by default as identity,
    order_id     bigint         not null,
    line_index   integer,
    menu_item_id varchar(255)   not null,
    item_name    varchar(255)   not null,
    quantity     integer        not null,
    size         varchar(255),
    is_meal      boolean        not null,
    notes        varchar(255),
    unit_price   numeric(10, 2) not null,
    primary key (id),
    constraint fk_order_line_orders
        foreign key (order_id) references orders
);

-- @ElementCollection of String (chosen add-on labels) on OrderLine
create table order_line_addon (
    order_line_id bigint       not null,
    addon         varchar(255),
    constraint fk_order_line_addon_order_line
        foreign key (order_line_id) references order_line
);

-- Index the kitchen rail / history query (status filter, created_at ordering).
create index idx_orders_status_created_at on orders (status, created_at);
