-- Staff table (Phase 7 — employee management). Mirrors com.ember.domain.Staff so
-- prod can keep running with ddl-auto: validate. Both credential hashes are nullable:
-- a member may have a PIN (stations), a password (admin), or both.
create table staff (
    id            bigint       generated by default as identity,
    username      varchar(255) not null,
    display_name  varchar(255) not null,
    role          varchar(255) not null,
    pin_hash      varchar(255),
    password_hash varchar(255),
    active        boolean      not null,
    created_at    timestamp(6) with time zone not null,
    primary key (id),
    constraint uq_staff_username unique (username)
);
