-- Time-clock & scheduling (Phase 11).

-- Actual hours worked: one open punch per staff member until they clock out.
create table time_entry (
    id        bigint generated by default as identity,
    staff_id  bigint not null,
    clock_in  timestamp(6) with time zone not null,
    clock_out timestamp(6) with time zone,
    primary key (id)
);

-- The roster: scheduled shifts.
create table shift (
    id         bigint generated by default as identity,
    staff_id   bigint  not null,
    work_date  date    not null,
    start_time time(6) not null,
    end_time   time(6) not null,
    note       varchar(255),
    primary key (id)
);
